spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/password_db
    username: postgres
    password: 8520
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
